import {Injectable} from '@nestjs/common';
import OpenAIApi from 'openai';
import {ConfigService} from "@nestjs/config";
import {defaultConfig} from "./model.configurations";
import {SingleDishInputDto} from "./dtos/single-dish-input.dto";
import {singleDishInstruction} from "./model.instructions";
import {SingleDishOutputDto} from "./dtos/single-dish-output.dto";
import {ImageDto} from "./dtos/image.dto";

@Injectable()
export class OpenaiService {
    private openai: OpenAIApi;

    constructor(private configService: ConfigService) {
        this.openai = new OpenAIApi({
            apiKey: process.env.OPEN_AI_SECRET_KEY,
        });
    }

    async generateDishImage(output: SingleDishOutputDto): Promise<ImageDto> {
        return this.openai.images.generate({
            model: 'dall-e-3',
            prompt: `Generate realistic picture of a dish using recipe data that was generated by gpt model. Data: ${JSON.stringify(output)}`,
            size: '1792x1024',
            quality: 'hd',
            n: 1,
        }).then(response => {
            return {url: response.data[0].url}
        } )
        ;
    }

    async generateSingleDishDefault(input: SingleDishInputDto): Promise<SingleDishOutputDto> {
        const response = await this.openai.responses.create(defaultConfig(input, singleDishInstruction));
        return JSON.parse(response.output_text);
    }

    async generateMealPlan() {
    }
}
